services:

  rc-postgres:
    image: postgres:14.10
    container_name: rc-postgres
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: redis-caching
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - rc-network
    volumes:
      - /data:/var/lib/postgresql/data

  rc-redis:
    image: redis:latest
    container_name: rc-redis
    hostname: localhost
    networks:
      - rc-network
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data

  redis-caching:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      rc-postgres:
        condition: service_healthy
        restart: true
      rc-redis:
        condition: service_started
    networks:
      - rc-network


networks:
  rc-network:
    driver: bridge

volumes:
  db:
    driver: local