spring:
  application:
    name: redis-caching
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/redis-caching
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: redis://localhost:6379
    timeout: 60000
  cache:
    redis:
      time-to-live: 180000 # Задаёт время существования параметра в кэше.
  data:
    redis:
      repositories:
        enabled: false